version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
      # - "8200-9000:8200-9000"
    volumes:
      - ${APP_CODE_PATH}:/var/www/:rw
      - ${CONF_NGINX_PATH}vhost:/etc/nginx/vhost/:rw
      - ${CONF_NGINX_PATH}nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CONF_NGINX_PATH}phalcon-admin.conf:/etc/nginx/phalcon-admin.conf:ro
      - ${CONF_NGINX_PATH}phalcon.conf:/etc/nginx/phalcon.conf:ro
      - ${CONF_NGINX_PATH}phalcon-rewrite.conf:/etc/nginx/phalcon-rewrite.conf:ro
      - ${CONF_NGINX_PATH}phalcon-admin-rewrite.conf:/etc/nginx/phalcon-admin-rewrite.conf:ro
      - ${CONF_NGINX_PATH}php-fpm.conf:/etc/nginx/php-fpm.conf:ro
      - ${CONF_NGINX_PATH}thinkphp.conf:/etc/nginx/thinkphp.conf:ro
      - ${CONF_NGINX_PATH}thinkphp-rewrite.conf:/etc/nginx/thinkphp-rewrite.conf:ro
      - ${CONF_PATH}hosts:/etc/hosts:rw
      - ${LOG_PATH}:/var/log/lnmp/:rw
      - ${CONF_PATH}localtime:/etc/localtime:rw
    restart: always
    networks:
      - net-php

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
      args:
        PHP_VERSION: ${PHP_VERSION}
        SOURCE_LIST: ${PHP_SOURCE_LIST}
        XDEBUG_VERSION: ${PHP_XDEBUG_VERSION}
        SWOOLE_VERSION: ${PHP_SWOOLE_VERSION}
        PAHCLON_VERSION: ${PHP_PAHCLON_VERSION}
        REDIS_VERSION: ${PHP_REDIS_VERSION}
        SUPPORT_MCRYPT: ${PHP_SUPPORT_MCRYPT}
        BUILT_IN_OPCACHE: ${PHP_BUILT_IN_OPCACHE}
        INSTALL_MONGO: ${PHP_INSTALL_MONGO}
        INSTALL_MEMCACHED: ${PHP_INSTALL_MEMCACHED}
        INSTALL_TIDEWAY: ${PHP_INSTALL_TIDEWAY}
    expose:
      - "9000"
    ports:
      - "9501:9501"
    volumes:
     - ${APP_CODE_PATH}:/var/www/:rw
     - ${CONF_PHP_PATH}php-${PHP_VERSION}.ini:/usr/local/etc/php/php.ini:ro
     - ${CONF_PHP_PATH}php-fpm-${PHP_VERSION}.conf:/usr/local/etc/php-fpm.d/www.conf:rw
     - ${CONF_PATH}hosts:/etc/hosts:rw
     - ${LOG_PATH}:/var/log/lnmp/:rw
     - ${CONF_PATH}localtime:/etc/localtime:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php
      - net-mysql
      - net-redis
      
  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${CONF_PATH}mysql.conf:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_PATH}mysql/:/var/lib/mysql/:rw
      - ${CONF_PATH}localtime:/etc/localtime:rw
      - ${LOG_PATH}mysql:/var/lib/mysql/:rw
    restart: always
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  redis:
    image: redis:4.0
    restart: always
    volumes:
      - ${DATA_PATH}redis:/data
      - ${CONF_PATH}redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ${CONF_PATH}localtime:/etc/localtime:rw
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - net-redis
    ports:
      - "${REDIS_PORT}:6379"

  portainer:
    image: portainer/portainer:latest
    ports:
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:cached
      - ${DATA_PATH}portainer/:/data:cached
      - ${CONF_PATH}localtime:/etc/localtime:rw
      
networks:
  net-php:
  net-mysql:
  net-redis:
